export const LOCAL_GUEST_SAVE_VERSION = 4;

export const LOCAL_CATALOG = {
  team_create_cost: 5000,
  payroll_cycle_min: 120,
  pool_refresh_min: 30,
  team_max_members: 4,
  base_caps: { employees: 4, vehicles: 2 },
  hr_costs: { promote_base: 1800, pool_refresh: 850, heal_base: 1200, release_base: 2200 },
  emp_level_xp: [0, 100, 260, 520, 900, 1400, 2050, 2850, 3800, 4900],
  ranks: ["recruta","membro","especialista","veterano","tenente","chefe_equipa","braco_direito"],
  rank_req_level: [1,2,3,4,6,8,10],
  team_specs: {
    assalto: { name:"Crew de Assalto", desc:"Força, entrada e controlo de operações de risco." },
    logistica: { name:"Rede Logística", desc:"Transporte, contrabando e operações dependentes de frota." },
    tecnica: { name:"Célula Técnica", desc:"Hacking, inteligência e operações discretas." },
    influencia: { name:"Unidade de Influência", desc:"Negociação, contactos, lavagem e pressão social." },
  },
  rarities: {
    comum:{name:"Comum", color:"#A1A1AA"}, raro:{name:"Raro", color:"#60A5FA"},
    elite:{name:"Elite", color:"#F59E0B"}, lendario:{name:"Lendário", color:"#F43F5E"},
  },
  rarity_min_respect: { comum:0, raro:300, elite:1500, lendario:5000 },
  specializations: {
    assaltante:{name:"Assaltante",spec:"assalto",salary:500,attrs:["forca","tiro","sangue_frio"]},
    motorista:{name:"Motorista",spec:"logistica",salary:450,attrs:["conducao","discricao","sangue_frio"]},
    hacker:{name:"Hacker",spec:"tecnica",salary:650,attrs:["hack","inteligencia","discricao"]},
    mecanico:{name:"Mecânico",spec:"logistica",salary:475,attrs:["inteligencia","resistencia","conducao"]},
    informador:{name:"Informador",spec:"influencia",salary:400,attrs:["negociacao","discricao","inteligencia"]},
    medico:{name:"Médico Clandestino",spec:"tecnica",salary:700,attrs:["inteligencia","sangue_frio","resistencia"]},
    lavador:{name:"Lavador de Dinheiro",spec:"influencia",salary:620,attrs:["inteligencia","negociacao","discricao"]},
    advogado:{name:"Advogado",spec:"influencia",salary:750,attrs:["negociacao","inteligencia","sangue_frio"]},
    negociador:{name:"Negociador",spec:"influencia",salary:560,attrs:["negociacao","inteligencia","sangue_frio"]},
    seguranca:{name:"Segurança",spec:"assalto",salary:470,attrs:["forca","resistencia","tiro"]},
    contrabandista:{name:"Contrabandista",spec:"logistica",salary:540,attrs:["conducao","negociacao","discricao"]},
    falsificador:{name:"Falsificador",spec:"tecnica",salary:560,attrs:["inteligencia","discricao","hack"]},
    espiao:{name:"Espião",spec:"tecnica",salary:650,attrs:["discricao","inteligencia","negociacao"]},
    gestor:{name:"Gestor de Empresa",spec:"influencia",salary:590,attrs:["inteligencia","negociacao","sangue_frio"]},
    sniper:{name:"Franco-Atirador",spec:"assalto",salary:640,attrs:["tiro","discricao","sangue_frio"]},
    arrombador:{name:"Arrombador",spec:"assalto",salary:500,attrs:["forca","discricao","inteligencia"]},
    piloto:{name:"Piloto de Fuga",spec:"logistica",salary:560,attrs:["conducao","sangue_frio","discricao"]},
    estafeta:{name:"Estafeta",spec:"logistica",salary:400,attrs:["conducao","resistencia","discricao"]},
    engenheiro_social:{name:"Engenheiro Social",spec:"influencia",salary:620,attrs:["negociacao","inteligencia","hack"]},
    criptografo:{name:"Criptógrafo",spec:"tecnica",salary:680,attrs:["hack","inteligencia","discricao"]},
    relacoes_publicas:{name:"Relações Públicas",spec:"influencia",salary:540,attrs:["negociacao","inteligencia","sangue_frio"]},
    chantagista:{name:"Chantagista",spec:"influencia",salary:560,attrs:["negociacao","discricao","sangue_frio"]},
    quimico:{name:"Químico",spec:"tecnica",salary:650,attrs:["inteligencia","sangue_frio","resistencia"]},
    recrutador:{name:"Recrutador",spec:"influencia",salary:500,attrs:["negociacao","inteligencia","discricao"]},
  },
  talents: {
    motorista_fantasma:{name:"Motorista Fantasma",desc:"Reduz tempos de viagem e melhora fugas."},
    contabilista_sujo:{name:"Contabilista Sujo",desc:"Melhora lavagem e eficiência financeira."},
    olhos_na_rua:{name:"Olhos na Rua",desc:"Melhora inteligência e descoberta de oportunidades."},
    mecanico_elite:{name:"Mecânico de Elite",desc:"Reduz desgaste e custos de reparação."},
    pontaria_letal:{name:"Pontaria Letal",desc:"Melhora operações de combate."},
    rei_da_noite:{name:"Rei da Noite",desc:"Bónus em operações discretas."},
    lingua_de_prata:{name:"Língua de Prata",desc:"Melhora negociação e influência."},
    fantasma_digital:{name:"Fantasma Digital",desc:"Melhora ações técnicas e hacking."},
    maos_de_seda:{name:"Mãos de Seda",desc:"Reduz calor em operações furtivas."},
    formula_secreta:{name:"Fórmula Secreta",desc:"Aumenta eficiência de operações especiais."},
  },
  recruit_sources: {
    rua:{name:"Rua",min_level:1}, bares:{name:"Bares",min_level:1}, empresas:{name:"Empresas",min_level:2},
    prisoes:{name:"Prisões",min_level:3}, mercado_negro:{name:"Mercado Negro",min_level:4}, contactos:{name:"Contactos",min_level:5},
  },
  training_courses: {
    combate:{name:"Combate",cost:950,duration_s:45}, conducao:{name:"Condução Evasiva",cost:700,duration_s:45},
    hacking:{name:"Hacking",cost:1400,duration_s:55}, discricao:{name:"Discrição",cost:900,duration_s:50},
    negociacao:{name:"Negociação",cost:850,duration_s:45}, primeiros_socorros:{name:"Primeiros Socorros",cost:450,duration_s:40},
    logistica:{name:"Logística",cost:650,duration_s:45}, gestao:{name:"Gestão",cost:1100,duration_s:50},
    lideranca:{name:"Liderança",cost:1200,duration_s:55}, treino_fisico:{name:"Treino Físico",cost:500,duration_s:100},
  },
  vehicle_models: {
    usado:{name:"Sedan Usado",min_level:1,price:12500,speed:9,fuel_type:"gasolina",tank_l:45,cons:8.0,seats:4,discretion:75,best_for:["logistica","influencia"],luxury:false},
    moto:{name:"Moto Rápida",min_level:1,price:9000,speed:15,fuel_type:"gasolina",tank_l:15,cons:4.5,seats:2,discretion:70,best_for:["assalto","tecnica"],luxury:false},
    van:{name:"Van Reforçada",min_level:2,price:26000,speed:12,fuel_type:"gasoleo",tank_l:70,cons:10.0,seats:6,discretion:80,best_for:["logistica"],luxury:false},
    desportivo:{name:"Desportivo",min_level:3,price:55000,speed:19,fuel_type:"gasolina",tank_l:55,cons:12.0,seats:2,discretion:15,best_for:["especial"],luxury:true},
    suv_blindado:{name:"SUV Blindado",min_level:4,price:95000,speed:14,fuel_type:"gasoleo",tank_l:80,cons:13.0,seats:5,discretion:35,best_for:["assalto"],luxury:false},
    supercarro:{name:"Supercarro",min_level:5,price:185000,speed:26,fuel_type:"gasolina",tank_l:60,cons:15.0,seats:2,discretion:8,best_for:["especial"],luxury:true},
    carrinha_entrega:{name:"Carrinha de Entregas",min_level:1,price:21000,speed:10,fuel_type:"gasolina",tank_l:50,cons:7.5,seats:3,discretion:85,best_for:["logistica"],luxury:false},
    berlina_blindada:{name:"Berlina Blindada",min_level:2,price:65000,speed:13,fuel_type:"gasoleo",tank_l:65,cons:11.0,seats:4,discretion:45,best_for:["influencia"],luxury:false},
    buggy_todo_terreno:{name:"Buggy Todo-o-Terreno",min_level:2,price:18000,speed:16,fuel_type:"gasolina",tank_l:40,cons:9.0,seats:2,discretion:25,best_for:["assalto"],luxury:false},
    limousine:{name:"Limousine",min_level:4,price:75000,speed:11,fuel_type:"gasolina",tank_l:70,cons:14.0,seats:6,discretion:5,best_for:["influencia","especial"],luxury:true},
    carro_furtivo:{name:"Carro Furtivo",min_level:5,price:48000,speed:20,fuel_type:"gasolina",tank_l:50,cons:10.0,seats:2,discretion:95,best_for:["tecnica","especial"],luxury:false},
  },
  fuel_prices:{gasolina:2.12,gasoleo:2.22},
  weapon_categories:{
    silenciosa:{name:"Silenciosa",desc:"Sem barulho, ideal para discrição."},
    equilibrada:{name:"Equilibrada",desc:"Sem requisitos, funciona em qualquer lado."},
    assalto:{name:"Assalto",desc:"Potência e cadência para operações de força."},
    assalto_especial:{name:"Assalto/Especial",desc:"Alta gama equilibrada."},
    assalto_pesado:{name:"Assalto Pesado",desc:"Supressão máxima para quem aguenta o peso."},
    tecnica_especial:{name:"Técnica/Especial",desc:"Precisão e alcance para operações de alto risco."},
  },
  weapon_models:{
    faca_taser:{name:"Faca/Taser",category:"silenciosa",min_level:1,price:180,power:15,accuracy:65,range:3,weight:5,use_speed:95,durability:90,reliability:95,magazine_capacity:1,maintenance_cost:40,discretion:95,best_for:["tecnica","influencia"],requires_attr:{},loud:false,desc:"Sem munições, silenciosa e discreta."},
    pistola:{name:"Pistola",category:"equilibrada",min_level:1,price:1500,power:40,accuracy:60,range:25,weight:20,use_speed:75,durability:70,reliability:85,magazine_capacity:15,maintenance_cost:120,discretion:45,best_for:["assalto","tecnica","influencia"],requires_attr:{},loud:true,desc:"Equilibrada e sem requisitos."},
    espingarda:{name:"Espingarda",category:"assalto",min_level:2,price:1400,power:85,accuracy:45,range:12,weight:55,use_speed:55,durability:65,reliability:80,magazine_capacity:6,maintenance_cost:150,discretion:20,best_for:["assalto"],requires_attr:{forca:4},loud:true,desc:"Potência elevada a curta distância."},
    submetralhadora:{name:"Submetralhadora",category:"assalto",min_level:3,price:7500,power:60,accuracy:50,range:30,weight:45,use_speed:90,durability:60,reliability:75,magazine_capacity:30,maintenance_cost:450,discretion:25,best_for:["assalto","especial"],requires_attr:{forca:3,tiro:4},loud:true,desc:"Cadência e carregador elevados."},
    pistola_silenciada:{name:"Pistola Silenciada",category:"silenciosa",min_level:3,price:4500,power:35,accuracy:75,range:20,weight:15,use_speed:85,durability:80,reliability:90,magazine_capacity:12,maintenance_cost:200,discretion:85,best_for:["tecnica","especial"],requires_attr:{discricao:4},loud:false,desc:"Discreta com poder de fogo real."},
    cacadeira_serrada:{name:"Caçadeira de Canos Serrados",category:"assalto",min_level:3,price:3000,power:95,accuracy:35,range:8,weight:40,use_speed:65,durability:45,reliability:60,magazine_capacity:2,maintenance_cost:180,discretion:15,best_for:["assalto"],requires_attr:{forca:5},loud:true,desc:"Devastadora à queima-roupa."},
    rifle_assalto:{name:"Rifle de Assalto",category:"assalto_especial",min_level:4,price:9000,power:75,accuracy:70,range:55,weight:60,use_speed:70,durability:75,reliability:85,magazine_capacity:25,maintenance_cost:450,discretion:30,best_for:["assalto","especial"],requires_attr:{tiro:5,forca:4},loud:true,desc:"Alta gama equilibrada."},
    rifle_precisao:{name:"Rifle de Precisão",category:"tecnica_especial",min_level:5,price:6500,power:90,accuracy:95,range:95,weight:70,use_speed:25,durability:80,reliability:80,magazine_capacity:5,maintenance_cost:650,discretion:65,best_for:["tecnica","especial"],requires_attr:{tiro:7,inteligencia:4},loud:false,desc:"Precisão e alcance máximos."},
    metralhadora_ligeira:{name:"Metralhadora Ligeira",category:"assalto_pesado",min_level:6,price:18000,power:88,accuracy:55,range:60,weight:90,use_speed:60,durability:85,reliability:82,magazine_capacity:100,maintenance_cost:900,discretion:5,best_for:["assalto","especial"],requires_attr:{forca:7,tiro:6},loud:true,desc:"Supressão total para operações pesadas."},
  },
  achievement_milestones:[10,25,50,100,250],
  achievement_bonus_pct_per_milestone:0.01,
  weapon_category_weights:{
    assalto:{power:.35,accuracy:.15,range:0,lightness:0,speed:.30,magazine:.20},
    tecnica:{power:.05,accuracy:.35,range:.25,lightness:.25,speed:.10,magazine:0},
    especial:{power:.25,accuracy:.25,range:.25,lightness:0,speed:.15,magazine:.10},
    influencia:{power:0,accuracy:.40,range:0,lightness:.35,speed:.25,magazine:0},
    logistica:{power:.20,accuracy:.20,range:0,lightness:.20,speed:.20,magazine:.20},
  },
  weapon_meta:{
    skill_floor:.55,skill_attr_cap:8,proficiency_max:100,proficiency_bonus_max_pct:.08,
    compatibility_min_factor:.4,condition_soft_knee:40,jam_reliability_weight:.4,
    jam_condition_threshold:60,jam_condition_weight:.25,jam_max:.35,jam_warn_risk:.15,
    durability_wear_ref:70,repair_cost_multiplier:.5,wear_per_mission:3,wear_risk_mult:.45,
    combat_score_scale:.15,bonus_min:-.05,bonus_max:.12,loud_heat_mult:1.3,
    proficiency_gain_per_mission:4,jam_chance_penalty:.04,jam_chance_penalty_cap:.12,
    jam_extra_wear:6,mismatch_penalty_max:.12,sell_fraction:.45,
  },
  team_meta:{},
  vehicle_category_weights:{
    assalto:{speed:.45,seats_fit:.25,discretion:.30},
    tecnica:{speed:.20,seats_fit:.20,discretion:.60},
    especial:{speed:.40,seats_fit:.20,discretion:.40},
    influencia:{speed:.15,seats_fit:.35,discretion:.50},
    logistica:{speed:.15,seats_fit:.55,discretion:.30},
  },
  fleet_meta:{sell_fraction:.4,repair_cost_pct:.003},
  property_meta:{
    maintenance_pct_per_day:.00008,
    condition_recovery_per_hour:2,
    condition_decay_per_hour:3,
    upgrade_base_s:90,
    upgrade_per_level_s:60,
    stack_diminish:[1,.7,.5],
    sell_fraction:.7,
    upgrade_cost_pct:.6,
  },
  property_max_level:3,
  property_types:{
    esconderijo:{name:"Esconderijo",desc:"Alarga a capacidade de operacionais.",min_level:1,price:85000,cap_employees:4,employee_cap:4},
    garagem:{name:"Garagem",desc:"Espaço extra para a frota.",min_level:1,price:55000,cap_vehicles:2,vehicle_cap:2},
    empresa_legal:{name:"Empresa de Fachada",desc:"Lava dinheiro sujo automaticamente.",min_level:2,price:140000,launder_per_h:1400,passive_clean:220},
    armazem:{name:"Armazém",desc:"Aumenta recompensas de logística.",min_level:2,price:180000,bonus_pct:.05,bonus_category:"logistica",bonus_label:"recompensas de logística"},
    laboratorio:{name:"Laboratório",desc:"Produz dinheiro sujo passivamente, mas gera calor.",min_level:3,price:220000,dirty_per_h:2100,heat_per_h:.8,passive_dirty:420},
    oficina:{name:"Oficina",desc:"Reduz o custo de reparações.",min_level:3,price:165000,repair_discount_pct:.15,repair_discount:.15},
    porto_clandestino:{name:"Porto Clandestino",desc:"Aumenta todas as recompensas.",min_level:4,price:420000,bonus_pct:.05,bonus_category:"all",bonus_label:"todas as recompensas"},
    posto_vigilancia:{name:"Posto de Vigilância",desc:"Aumenta recompensas técnicas.",min_level:2,price:95000,bonus_pct:.05,bonus_category:"tecnica",bonus_label:"recompensas técnicas"},
    escritorio_advocacia:{name:"Escritório de Advocacia",desc:"Aumenta recompensas de influência.",min_level:2,price:220000,bonus_pct:.05,bonus_category:"influencia",bonus_label:"recompensas de influência",legal_bonus:.18},
    arsenal:{name:"Arsenal",desc:"Aumenta recompensas de assalto.",min_level:3,price:140000,bonus_pct:.05,bonus_category:"assalto",bonus_label:"recompensas de assalto"},
    casa_cambio:{name:"Casa de Câmbio",desc:"Lavagem automática avançada.",min_level:3,price:280000,launder_per_h:1750,passive_clean:620},
    centro_logistico:{name:"Centro Logístico",desc:"Amplia bastante a capacidade da frota.",min_level:4,price:450000,cap_vehicles:3,vehicle_cap:3},
  },
  hq_max_level:8,
  hq_default_priority:"equilibrio",
  hq_priorities:{
    equilibrio:"Equilíbrio", dinheiro:"Capital", discricao:"Discrição", crescimento:"Crescimento", operacoes:"Operações",
  },
  hq_level_benefits:[
    {level:1,min_org_level:1,upgrade_cost:0,unlocks:["operacoes"]},
    {level:2,min_org_level:2,upgrade_cost:15000,unlocks:["rh"]},
    {level:3,min_org_level:3,upgrade_cost:30000,unlocks:["logistica"]},
    {level:4,min_org_level:4,upgrade_cost:55000,unlocks:["inteligencia"]},
    {level:5,min_org_level:5,upgrade_cost:90000,unlocks:["financas"]},
    {level:6,min_org_level:6,upgrade_cost:140000,unlocks:["seguranca"]},
    {level:7,min_org_level:8,upgrade_cost:220000,unlocks:["estrategia"]},
    {level:8,min_org_level:10,upgrade_cost:350000,unlocks:["legado"]},
  ],
  hq_departments:{
    operacoes:{name:"Operações",desc:"Coordenação de equipas e missões."},
    rh:{name:"Recursos Humanos",desc:"Recrutamento e desenvolvimento."},
    logistica:{name:"Logística",desc:"Frota e capacidade."},
    inteligencia:{name:"Inteligência",desc:"Reconhecimento e previsão."},
    financas:{name:"Finanças",desc:"Lavagem e reservas."},
    seguranca:{name:"Segurança",desc:"Proteção do império."},
    estrategia:{name:"Estratégia",desc:"Planeamento avançado."},
    legado:{name:"Legado",desc:"Bónus de endgame."},
  },
  opportunity_types:{
    assalto_loja:{name:"Assalto a Estabelecimento",category:"assalto"},
    transporte_clandestino:{name:"Transporte Clandestino",category:"logistica"},
    fraude_digital:{name:"Intrusão Digital",category:"tecnica"},
    extorsao:{name:"Pressão Empresarial",category:"influencia"},
    roubo_carga:{name:"Roubo de Carga",category:"assalto"},
    contrabando:{name:"Rota de Contrabando",category:"logistica"},
    espionagem:{name:"Espionagem Corporativa",category:"tecnica"},
    negociacao:{name:"Acordo de Bastidores",category:"influencia"},
  },
  economy_meta:{
    employer_social_security_rate:.2375,
    economic_week_minutes:120,
    vehicle_annual_fixed_costs:{
      usado:1250,moto:700,van:1800,desportivo:2500,suv_blindado:3600,
      supercarro:6000,carrinha_entrega:1600,berlina_blindada:3000,
      buggy_todo_terreno:1200,limousine:3600,carro_furtivo:2400,
    },
    launder_base_rate:.78,
    launder_max_rate:.90,
    launder_passive_rate:.82,
    mission_rewards:{
      min:1500,max:90000,
      base_by_risk:{1:2500,2:4800,3:9000,4:16500,5:30000},
      org_level_per_level:.12,
      category_mult:{assalto:1.05,logistica:.95,tecnica:1.10,influencia:.90,especial:1.25},
      rare_mult:1.6,
    },
  },
  shop:{
    speedup_cost_per_min:140,
    speedup_cost_min:500,
    slot_cost_vehicle_base:8000,
    slot_cost_employee_base:6500,
    slot_cost_scale_per_unit:0.35,
    vip_plans:{
      week:{label:"VIP 7 dias",name:"VIP 7 dias",days:7,cost:18000,price:18000,description:"Bónus de qualidade de vida durante 7 dias."},
      month:{label:"VIP 30 dias",name:"VIP 30 dias",days:30,cost:52000,price:52000,description:"Bónus de qualidade de vida durante 30 dias."},
    },
    vehicle_paints:{
      graphite:{label:"Grafite",name:"Grafite",color:"#52525B",cost:2500,price:2500},
      midnight:{label:"Midnight",name:"Midnight",color:"#111827",cost:3500,price:3500},
      crimson:{label:"Crimson",name:"Crimson",color:"#991B1B",cost:4000,price:4000},
    },
    team_emblems:{
      wolf:{label:"Lobo",name:"Lobo",color:"#94A3B8",cost:2200,price:2200},
      crown:{label:"Coroa",name:"Coroa",color:"#EAB308",cost:3000,price:3000},
      ghost:{label:"Fantasma",name:"Fantasma",color:"#A78BFA",cost:3500,price:3500},
    },
    hq_skins:{
      bunker:{label:"Bunker",name:"Bunker",color:"#475569",cost:6500,price:6500},
      marble:{label:"Mármore Negro",name:"Mármore Negro",color:"#27272A",cost:8500,price:8500},
      neon:{label:"Neon Tático",name:"Neon Tático",color:"#EF4444",cost:9000,price:9000},
    },
  },
};
