export const LOCAL_GUEST_SAVE_VERSION = 1;

export const LOCAL_CATALOG = {
  team_create_cost: 5000,
  payroll_cycle_min: 120,
  pool_refresh_min: 30,
  team_max_members: 4,
  base_caps: { employees: 4, vehicles: 2 },
  hr_costs: { promote_base: 1800, pool_refresh: 850, heal_base: 1200, release_base: 2200 },
  emp_level_xp: [0, 100, 260, 520, 900, 1400, 2050, 2850, 3800, 4900],
  ranks: ["recruta","membro","especialista","veterano","tenente","chefe_equipa","braco_direito"],
  rank_req_level: [1,2,3,4,5,6,8],
  team_specs: {
    assalto: { name:"Crew de Assalto", desc:"Força, entrada e controlo de operações de risco." },
    logistica: { name:"Rede Logística", desc:"Transporte, contrabando e operações dependentes de frota." },
    tecnica: { name:"Célula Técnica", desc:"Hacking, inteligência e operações discretas." },
    influencia: { name:"Unidade de Influência", desc:"Negociação, contactos, lavagem e pressão social." },
  },
  rarities: {
    comum:{name:"Comum", color:"#A1A1AA"}, raro:{name:"Raro", color:"#60A5FA"},
    elite:{name:"Elite", color:"#F59E0B"}, lendario:{name:"Lendário", color:"#F43F5E"},
  },
  rarity_min_respect: { comum:0, raro:300, elite:1500, lendario:5000 },
  specializations: {
    assaltante:{name:"Assaltante",spec:"assalto",salary:520,attrs:["forca","tiro","sangue_frio"]},
    motorista:{name:"Motorista",spec:"logistica",salary:500,attrs:["conducao","discricao","sangue_frio"]},
    hacker:{name:"Hacker",spec:"tecnica",salary:650,attrs:["hack","inteligencia","discricao"]},
    mecanico:{name:"Mecânico",spec:"logistica",salary:540,attrs:["inteligencia","resistencia","conducao"]},
    informador:{name:"Informador",spec:"influencia",salary:460,attrs:["negociacao","discricao","inteligencia"]},
    medico:{name:"Médico Clandestino",spec:"tecnica",salary:700,attrs:["inteligencia","sangue_frio","resistencia"]},
    lavador:{name:"Lavador de Dinheiro",spec:"influencia",salary:720,attrs:["inteligencia","negociacao","discricao"]},
    advogado:{name:"Advogado",spec:"influencia",salary:760,attrs:["negociacao","inteligencia","sangue_frio"]},
    negociador:{name:"Negociador",spec:"influencia",salary:600,attrs:["negociacao","inteligencia","sangue_frio"]},
    seguranca:{name:"Segurança",spec:"assalto",salary:540,attrs:["forca","resistencia","tiro"]},
    contrabandista:{name:"Contrabandista",spec:"logistica",salary:580,attrs:["conducao","negociacao","discricao"]},
    falsificador:{name:"Falsificador",spec:"tecnica",salary:620,attrs:["inteligencia","discricao","hack"]},
    espiao:{name:"Espião",spec:"tecnica",salary:740,attrs:["discricao","inteligencia","negociacao"]},
    gestor:{name:"Gestor de Empresa",spec:"influencia",salary:680,attrs:["inteligencia","negociacao","sangue_frio"]},
    sniper:{name:"Franco-Atirador",spec:"assalto",salary:720,attrs:["tiro","discricao","sangue_frio"]},
    arrombador:{name:"Arrombador",spec:"assalto",salary:560,attrs:["forca","discricao","inteligencia"]},
    piloto:{name:"Piloto de Fuga",spec:"logistica",salary:700,attrs:["conducao","sangue_frio","discricao"]},
    estafeta:{name:"Estafeta",spec:"logistica",salary:430,attrs:["conducao","resistencia","discricao"]},
    engenheiro_social:{name:"Engenheiro Social",spec:"influencia",salary:670,attrs:["negociacao","inteligencia","hack"]},
    criptografo:{name:"Criptógrafo",spec:"tecnica",salary:720,attrs:["hack","inteligencia","discricao"]},
    relacoes_publicas:{name:"Relações Públicas",spec:"influencia",salary:620,attrs:["negociacao","inteligencia","sangue_frio"]},
    chantagista:{name:"Chantagista",spec:"influencia",salary:640,attrs:["negociacao","discricao","sangue_frio"]},
    quimico:{name:"Químico",spec:"tecnica",salary:690,attrs:["inteligencia","sangue_frio","resistencia"]},
    recrutador:{name:"Recrutador",spec:"influencia",salary:570,attrs:["negociacao","inteligencia","discricao"]},
  },
  talents: {
    motorista_fantasma:{name:"Motorista Fantasma",desc:"Reduz tempos de viagem e melhora fugas."},
    contabilista_sujo:{name:"Contabilista Sujo",desc:"Melhora lavagem e eficiência financeira."},
    olhos_na_rua:{name:"Olhos na Rua",desc:"Melhora inteligência e descoberta de oportunidades."},
    mecanico_elite:{name:"Mecânico de Elite",desc:"Reduz desgaste e custos de reparação."},
    pontaria_letal:{name:"Pontaria Letal",desc:"Melhora operações de combate."},
    rei_da_noite:{name:"Rei da Noite",desc:"Bónus em operações discretas."},
    lingua_de_prata:{name:"Língua de Prata",desc:"Melhora negociação e influência."},
    fantasma_digital:{name:"Fantasma Digital",desc:"Melhora ações técnicas e hacking."},
    maos_de_seda:{name:"Mãos de Seda",desc:"Reduz calor em operações furtivas."},
    formula_secreta:{name:"Fórmula Secreta",desc:"Aumenta eficiência de operações especiais."},
  },
  recruit_sources: {
    rua:{name:"Rua",min_level:1}, bares:{name:"Bares",min_level:1}, empresas:{name:"Empresas",min_level:2},
    prisoes:{name:"Prisões",min_level:3}, mercado_negro:{name:"Mercado Negro",min_level:4}, contactos:{name:"Contactos",min_level:5},
  },
  training_courses: {
    combate:{name:"Combate",cost:950,duration_s:45}, conducao:{name:"Condução Evasiva",cost:900,duration_s:45},
    hacking:{name:"Hacking",cost:1200,duration_s:55}, discricao:{name:"Discrição",cost:1000,duration_s:50},
    negociacao:{name:"Negociação",cost:950,duration_s:45}, primeiros_socorros:{name:"Primeiros Socorros",cost:850,duration_s:40},
    logistica:{name:"Logística",cost:900,duration_s:45}, gestao:{name:"Gestão",cost:1100,duration_s:50},
    lideranca:{name:"Liderança",cost:1250,duration_s:55}, fisico:{name:"Treino Físico",cost:700,duration_s:35},
  },
  vehicle_models: {
    usado:{name:"Sedan Usado",min_level:1,price:6000,speed:9,seats:4,discretion:75,fuel_type:"gasolina",tank_l:50,cons:7.2},
    moto:{name:"Moto Rápida",min_level:1,price:12000,speed:15,seats:2,discretion:70,fuel_type:"gasolina",tank_l:17,cons:4.5},
    carrinha:{name:"Carrinha de Entregas",min_level:1,price:9000,speed:10,seats:3,discretion:85,fuel_type:"diesel",tank_l:65,cons:8.2},
    van:{name:"Van Reforçada",min_level:2,price:18000,speed:12,seats:6,discretion:80,fuel_type:"diesel",tank_l:75,cons:10.4},
    berlina:{name:"Berlina Blindada",min_level:2,price:22000,speed:13,seats:4,discretion:45,fuel_type:"gasolina",tank_l:65,cons:11.0},
    buggy:{name:"Buggy Todo-o-Terreno",min_level:2,price:20000,speed:16,seats:2,discretion:25,fuel_type:"gasolina",tank_l:48,cons:9.8},
    desportivo:{name:"Desportivo",min_level:3,price:30000,speed:19,seats:2,discretion:15,fuel_type:"gasolina",tank_l:60,cons:12.5},
    suv:{name:"SUV Blindado",min_level:4,price:45000,speed:14,seats:5,discretion:35,fuel_type:"diesel",tank_l:85,cons:13.2},
    limousine:{name:"Limousine",min_level:4,price:50000,speed:11,seats:6,discretion:5,fuel_type:"gasolina",tank_l:80,cons:14.0},
    supercarro:{name:"Supercarro",min_level:5,price:65000,speed:26,seats:2,discretion:8,fuel_type:"gasolina",tank_l:70,cons:16.5},
    furtivo:{name:"Carro Furtivo",min_level:5,price:55000,speed:20,seats:2,discretion:95,fuel_type:"gasolina",tank_l:58,cons:9.5},
  },
  fuel_prices:{gasolina:1.78,diesel:1.66},
  weapon_categories:{
    melee:{name:"Corpo a corpo"}, pistol:{name:"Pistolas"}, shotgun:{name:"Caçadeiras"},
    smg:{name:"Submetralhadoras"}, rifle:{name:"Rifles"}, lmg:{name:"Metralhadoras"},
  },
  weapon_models:{
    faca:{name:"Faca/Taser",category:"melee",min_level:1,price:1200,power:3,accuracy:8,range:1,weight:1,use_speed:9,durability:9,reliability:10,magazine:1,maintenance:1,discretion:100,best_for:["furtivo"]},
    pistola:{name:"Pistola",category:"pistol",min_level:1,price:2800,power:5,accuracy:7,range:5,weight:2,use_speed:8,durability:8,reliability:8,magazine:15,maintenance:3,discretion:55,best_for:["assalto"]},
    espingarda:{name:"Espingarda",category:"shotgun",min_level:2,price:5000,power:8,accuracy:5,range:4,weight:5,use_speed:5,durability:8,reliability:8,magazine:6,maintenance:4,discretion:20,best_for:["assalto"]},
    smg:{name:"Submetralhadora",category:"smg",min_level:3,price:10000,power:7,accuracy:6,range:6,weight:4,use_speed:9,durability:7,reliability:7,magazine:30,maintenance:5,discretion:25,best_for:["assalto"]},
    silenciada:{name:"Pistola Silenciada",category:"pistol",min_level:3,price:8000,power:5,accuracy:8,range:5,weight:2,use_speed:8,durability:7,reliability:8,magazine:12,maintenance:5,discretion:92,best_for:["furtivo"]},
    serrada:{name:"Caçadeira de Canos Serrados",category:"shotgun",min_level:3,price:6500,power:9,accuracy:4,range:2,weight:3,use_speed:7,durability:7,reliability:8,magazine:2,maintenance:4,discretion:10,best_for:["assalto"]},
    rifle:{name:"Rifle de Assalto",category:"rifle",min_level:4,price:18000,power:9,accuracy:7,range:8,weight:6,use_speed:7,durability:8,reliability:8,magazine:30,maintenance:6,discretion:10,best_for:["assalto"]},
    precisao:{name:"Rifle de Precisão",category:"rifle",min_level:5,price:32000,power:10,accuracy:10,range:10,weight:7,use_speed:3,durability:7,reliability:9,magazine:8,maintenance:8,discretion:20,best_for:["especial"]},
    lmg:{name:"Metralhadora Ligeira",category:"lmg",min_level:6,price:45000,power:10,accuracy:6,range:8,weight:9,use_speed:6,durability:9,reliability:8,magazine:80,maintenance:9,discretion:0,best_for:["assalto"]},
  },
  property_max_level:3,
  property_types:{
    esconderijo:{name:"Esconderijo",desc:"Aumenta capacidade de operacionais.",min_level:1,price:12000,employee_cap:2},
    garagem:{name:"Garagem",desc:"Aumenta capacidade da frota.",min_level:1,price:14000,vehicle_cap:2},
    fachada:{name:"Empresa de Fachada",desc:"Lava uma parte do dinheiro automaticamente.",min_level:2,price:26000,passive_clean:220},
    armazem:{name:"Armazém",desc:"Melhora logística e capacidade operacional.",min_level:2,price:24000,bonus_pct:0.04,bonus_category:"logistica"},
    laboratorio:{name:"Laboratório",desc:"Produz dinheiro sujo mas aumenta exposição.",min_level:3,price:38000,passive_dirty:420},
    oficina:{name:"Oficina",desc:"Reduz custos de reparação.",min_level:3,price:32000,repair_discount:0.15},
    porto:{name:"Porto Clandestino",desc:"Bónus global de recompensas.",min_level:4,price:60000,bonus_pct:0.08,bonus_category:"all"},
    vigilancia:{name:"Posto de Vigilância",desc:"Bónus técnico e informação territorial.",min_level:3,price:36000,bonus_pct:0.06,bonus_category:"tecnica"},
    advocacia:{name:"Escritório de Advocacia",desc:"Reduz consequências legais.",min_level:4,price:52000,legal_bonus:0.18},
    arsenal:{name:"Arsenal",desc:"Melhora operações de assalto.",min_level:4,price:50000,bonus_pct:0.08,bonus_category:"assalto"},
    cambio:{name:"Casa de Câmbio",desc:"Lavagem automática avançada.",min_level:5,price:75000,passive_clean:620},
    centro_logistico:{name:"Centro Logístico",desc:"Aumenta significativamente a capacidade da frota.",min_level:5,price:82000,vehicle_cap:4},
  },
  hq_max_level:8,
  hq_default_priority:"equilibrio",
  hq_priorities:{
    equilibrio:"Equilíbrio", dinheiro:"Capital", discricao:"Discrição", crescimento:"Crescimento", operacoes:"Operações",
  },
  hq_level_benefits:[
    {level:1,min_org_level:1,upgrade_cost:0,unlocks:["operacoes"]},
    {level:2,min_org_level:2,upgrade_cost:15000,unlocks:["rh"]},
    {level:3,min_org_level:3,upgrade_cost:30000,unlocks:["logistica"]},
    {level:4,min_org_level:4,upgrade_cost:55000,unlocks:["inteligencia"]},
    {level:5,min_org_level:5,upgrade_cost:90000,unlocks:["financas"]},
    {level:6,min_org_level:6,upgrade_cost:140000,unlocks:["seguranca"]},
    {level:7,min_org_level:8,upgrade_cost:220000,unlocks:["estrategia"]},
    {level:8,min_org_level:10,upgrade_cost:350000,unlocks:["legado"]},
  ],
  hq_departments:{
    operacoes:{name:"Operações",desc:"Coordenação de equipas e missões."},
    rh:{name:"Recursos Humanos",desc:"Recrutamento e desenvolvimento."},
    logistica:{name:"Logística",desc:"Frota e capacidade."},
    inteligencia:{name:"Inteligência",desc:"Reconhecimento e previsão."},
    financas:{name:"Finanças",desc:"Lavagem e reservas."},
    seguranca:{name:"Segurança",desc:"Proteção do império."},
    estrategia:{name:"Estratégia",desc:"Planeamento avançado."},
    legado:{name:"Legado",desc:"Bónus de endgame."},
  },
  opportunity_types:{
    assalto_loja:{name:"Assalto a Estabelecimento",category:"assalto"},
    transporte_clandestino:{name:"Transporte Clandestino",category:"logistica"},
    fraude_digital:{name:"Intrusão Digital",category:"tecnica"},
    extorsao:{name:"Pressão Empresarial",category:"influencia"},
    roubo_carga:{name:"Roubo de Carga",category:"assalto"},
    contrabando:{name:"Rota de Contrabando",category:"logistica"},
    espionagem:{name:"Espionagem Corporativa",category:"tecnica"},
    negociacao:{name:"Acordo de Bastidores",category:"influencia"},
  },
  achievement_milestones:[10,25,50,100,250],
  achievement_bonus_pct_per_milestone:0.01,
  weapon_category_weights:{},
  weapon_meta:{repair_cost_multiplier:0.35,sell_fraction:0.45},
  team_meta:{},
  vehicle_category_weights:{},
  fleet_meta:{sell_fraction:0.4,repair_cost_pct:0.002},
  property_meta:{sell_fraction:0.7,upgrade_cost_pct:0.6},
  quest_meta:{},
  shop:{
    speedup_cost_per_min:140,speedup_cost_min:500,
    slot_cost_vehicle_base:8000,slot_cost_employee_base:6500,slot_cost_scale_per_unit:0.35,
    vip_plans:{
      week:{name:"VIP 7 dias",days:7,price:18000,description:"Bónus de qualidade de vida durante 7 dias."},
      month:{name:"VIP 30 dias",days:30,price:52000,description:"Bónus de qualidade de vida durante 30 dias."},
    },
    vehicle_paints:{
      graphite:{name:"Grafite",price:2500}, midnight:{name:"Midnight",price:3500}, crimson:{name:"Crimson",price:4000},
    },
    team_emblems:{
      wolf:{name:"Lobo",price:2200}, crown:{name:"Coroa",price:3000}, ghost:{name:"Fantasma",price:3500},
    },
    hq_skins:{
      bunker:{name:"Bunker",price:6500}, marble:{name:"Mármore Negro",price:8500}, neon:{name:"Neon Tático",price:9000},
    },
  },
};
