"""live_phrases_beats.py — Beats de operação ESPECÍFICOS por tipo de missão.

Cada um dos 67 tipos de oportunidade tem 7 beats narrativos únicos, escritos
como (stage, speaker, text):
  stage 1 = chegada/entrada no alvo · stage 2 = execução · stage 3 = reta final
  speaker: "LÍDER" | "VIGIA" | "CONDUTOR" | "{X}" (membro aleatório) | "CENTRAL"
Placeholders suportados no texto: {district}, {team}, {vehicle}, {opp}.
O live_ops.PhraseDeck escolhe beats evitando os usados nas últimas missões da
organização (memória persistida) e preserva o arco narrativo por stage.
"""

TYPE_BEATS = {
    # ------------------------------------------------------------------
    # ASSALTO
    # ------------------------------------------------------------------
    "assalto": [
        (1, "VIGIA", "Montra escura, rua morta. Entrada pelas traseiras confirmada."),
        (1, "{X}", "Fechadura de três pinos — brincadeira de crianças. Estamos dentro."),
        (2, "{X}", "Caixa registadora aberta. A esvaziar prateleiras de valor."),
        (2, "LÍDER", "Dois minutos no relógio. Só levamos o que vale a pena carregar."),
        (2, "VIGIA", "Rua continua limpa. Um gato e um bêbado — nada que nos veja."),
        (3, "{X}", "Sacos cheios. Última varredura ao balcão."),
        (3, "LÍDER", "Apagar luzes, fechar a porta como estava. Saímos como entrámos."),
    ],
    "roubo": [
        (1, "VIGIA", "Alvo estacionado onde o informador disse. Sem alarme visível."),
        (1, "{X}", "Cunha na porta... trinco cedeu. Estou ao volante."),
        (2, "{X}", "Ignição eletrónica — a ligar por baixo da coluna. Trinta segundos."),
        (2, "CONDUTOR", "Motor acordou à primeira. Este bebé quer vir connosco."),
        (2, "VIGIA", "Dono ainda no café do outro lado. Nem sonha."),
        (3, "CONDUTOR", "A rolar devagar até à esquina — sem pressas, sem faróis."),
        (3, "LÍDER", "Matrícula trocada no primeiro beco. Carro fantasma."),
    ],
    "ataque_territorio": [
        (1, "VIGIA", "Sentinelas deles no ponto habitual. Dois à porta, um no telhado."),
        (1, "LÍDER", "Cercar o quarteirão. Ninguém entra nem sai sem nós sabermos."),
        (2, "{X}", "Primeiro posto deles caiu sem um tiro. Amarrados na cave."),
        (2, "LÍDER", "A empurrar a linha rua a rua. Eles estão a recuar."),
        (2, "VIGIA", "Reforços deles a chegar de mota — dois. Já foram tratados."),
        (3, "{X}", "O ponto de venda é nosso. A marcar presença na esquina."),
        (3, "LÍDER", "Bandeira trocada. Que a concorrência tome nota."),
    ],
    "assalto_armado": [
        (1, "LÍDER", "Máscaras. Três, dois, um — porta dentro, vozes altas."),
        (1, "{X}", "Toda a gente no chão! Segurança desarmado à entrada."),
        (2, "{X}", "Caixas a abrir gavetas. O gerente está a colaborar."),
        (2, "VIGIA", "Relógio na porta: noventa segundos. Rua ainda cega."),
        (2, "LÍDER", "Sem heróis hoje. O cofre pequeno também vem."),
        (3, "{X}", "Notas ensacadas, tinta de segurança separada. A recuar em formação."),
        (3, "LÍDER", "Saída em leque, veículos separados. Encontramo-nos no ponto morto."),
    ],
    "roubo_joalharia": [
        (1, "VIGIA", "Vitrines iluminadas, alarme de contacto na porta. Vamos pela clarabóia."),
        (1, "{X}", "Sensor de vidro neutralizado. A descer para o piso de vendas."),
        (2, "{X}", "Diamantes primeiro, relógios depois. O martelo é o último recurso."),
        (2, "{X}", "Vitrine principal aberta com ventosa — nem um estalido."),
        (2, "LÍDER", "Peso não interessa, quilates sim. Deixem a prata barata."),
        (3, "VIGIA", "Alarme silencioso intacto. Ninguém sabe que cá estivemos."),
        (3, "LÍDER", "Subir pela corda, fechar a clarabóia. Um trabalho de veludo."),
    ],
    "assalto_licorista": [
        (1, "VIGIA", "Loja fecha em cinco minutos. O empregado está sozinho."),
        (1, "{X}", "Entrada pela porta da frente com o último cliente. Discretos."),
        (2, "{X}", "Caixa do dia entregue sem drama. Ele já passou por isto."),
        (2, "{X}", "Garrafeira reservada atrás do balcão — os malte de 30 anos vêm connosco."),
        (2, "LÍDER", "Câmara do canto arrancada com cabo e tudo."),
        (3, "{X}", "Grade de garrafas no carrinho. Parece uma entrega normal."),
        (3, "LÍDER", "Persiana meio corrida, luz apagada. Loja fechou mais cedo hoje."),
    ],
    "roubo_carga": [
        (1, "VIGIA", "Camião parado na área de serviço, motorista a jantar. Vinte minutos de janela."),
        (1, "{X}", "Selo do reboque cortado. Porta dupla aberta."),
        (2, "{X}", "Paletes com mercadoria certa — o manifesto não mentia."),
        (2, "CONDUTOR", "A nossa carrinha encostada porta com porta. Transbordo em curso."),
        (2, "VIGIA", "Motorista pediu sobremesa. Abençoado apetite."),
        (3, "{X}", "Última palete. Selo falso colocado — ele só dá por isto na entrega."),
        (3, "CONDUTOR", "Saída pela traseira do parque, luzes mínimas."),
    ],
    "assalto_penhores": [
        (1, "VIGIA", "Casa de penhores com grade dupla. O dono dorme por cima da loja."),
        (1, "{X}", "Grade levantada com macaco hidráulico. Vidro cortado em meia-lua."),
        (2, "{X}", "Balcão das joias penhoradas aberto. Muita história aqui dentro."),
        (2, "{X}", "Cofre antigo, segredo de roda. Dá-me silêncio... três... esquerda..."),
        (2, "LÍDER", "Instrumentos e ouro. As televisões ficam — peso morto."),
        (3, "VIGIA", "Luz acendeu no primeiro andar — congelar... apagou. Continuamos."),
        (3, "LÍDER", "Sacos fechados. Baixar a grade como estava, à polegada."),
    ],
    "assalto_blindado": [
        (1, "VIGIA", "Blindado a entrar na rua de serviço — mesmo à hora prevista."),
        (1, "LÍDER", "Bloqueio à frente, camião nosso atrás. Ratoeira fechada."),
        (2, "{X}", "Guardas contidos, sem ferimentos. A carga é o que interessa."),
        (2, "{X}", "Rebarbadora na fechadura traseira. Faíscas e paciência."),
        (2, "LÍDER", "Malotes com selo do banco — é este o dinheiro que procurávamos."),
        (3, "{X}", "Transbordo completo. GPS do blindado ficou num camião do lixo."),
        (3, "CONDUTOR", "Dispersar por três rotas. Ninguém segue o mesmo caminho."),
    ],
    "emboscada_rival": [
        (1, "VIGIA", "Comitiva rival avistada — dois carros, como o informador prometeu."),
        (1, "LÍDER", "Posições na paralela. Esperem o meu sinal, nem um segundo antes."),
        (2, "{X}", "Pneus da frente rebentados. Eles estão encurralados no beco."),
        (2, "LÍDER", "Mostrem-lhes que isto é sério. Mas quero todos vivos — é um recado."),
        (2, "{X}", "O braço-direito deles entregou a pasta sem discutir."),
        (3, "{X}", "Mercadoria e telefones deles connosco. Ficam a pé e calados."),
        (3, "LÍDER", "Recado entregue. Eles sabem quem manda nesta zona."),
    ],
    "assalto_casino": [
        (1, "VIGIA", "Sala de contagem muda de turno às três. Câmaras em loop dentro de portas."),
        (1, "{X}", "Crachá clonado passou no torniquete de serviço. Estou no corredor técnico."),
        (2, "{X}", "Sala de contagem aberta. Isto é mais dinheiro do que já vi junto."),
        (2, "{X}", "Fichas de alto valor também — a caixa forte lateral cedeu."),
        (2, "LÍDER", "Calma nos corredores. Lá fora é só mais uma noite de sorte."),
        (3, "VIGIA", "Segurança do piso distraído com um jackpot combinado. Timing perfeito."),
        (3, "LÍDER", "Saída pela doca de fornecedores. A casa perdeu — para variar."),
    ],
    "sequestro_relampago": [
        (1, "VIGIA", "Alvo saiu do prédio à hora do costume. Sozinho, ao telemóvel."),
        (1, "{X}", "Recolhido em quatro segundos. Nem o café dele caiu ao chão."),
        (2, "CONDUTOR", "Rota de arrefecimento em curso — oito quarteirões de curvas."),
        (2, "{X}", "Ele percebeu a mensagem depressa. Está a ligar a quem tem de ligar."),
        (2, "LÍDER", "Transferência confirmada pelo contacto. Metade agora, metade na entrega."),
        (3, "{X}", "Entregue onde combinado, assustado mas inteiro. Sem marcas."),
        (3, "LÍDER", "Ele não vai à polícia. Sabe bem porquê."),
    ],
    "assalto_museu": [
        (1, "VIGIA", "Ronda noturna passa na ala oeste de vinte em vinte minutos. Janela aberta."),
        (1, "{X}", "Sensores de peso da sala principal em manutenção — o dossier estava certo."),
        (2, "{X}", "Moldura fora da parede. Tela enrolada com luvas de seda."),
        (2, "{X}", "Vitrine climatizada aberta pelo painel de serviço. A peça está na mala."),
        (2, "LÍDER", "Só as três peças da lista. O colecionador é específico."),
        (3, "VIGIA", "Guarda a fazer a ronda dois minutos adiantado — escondidos... passou."),
        (3, "LÍDER", "Réplicas no lugar. Vão demorar semanas a dar pela troca."),
    ],
    "guerra_territorio": [
        (1, "VIGIA", "A praça está tensa. Os homens deles sabem que vimos aí."),
        (1, "LÍDER", "Três frentes, avanço coordenado. Hoje isto fica resolvido."),
        (2, "{X}", "Frente norte a ceder. Eles não esperavam tanta gente nossa."),
        (2, "{X}", "Armazém deles tomado — mercadoria e livros de contas apreendidos."),
        (2, "LÍDER", "O tenente deles quer negociar. Agora quer negociar."),
        (3, "{X}", "Termos aceites: eles saem até ao fim da semana. A zona é nossa."),
        (3, "LÍDER", "Postos nossos em cada esquina. Que se lembrem desta noite."),
    ],
    # ------------------------------------------------------------------
    # INFLUÊNCIA
    # ------------------------------------------------------------------
    "cobranca": [
        (1, "VIGIA", "O devedor está no escritório dele. Sozinho, a fingir que trabalha."),
        (1, "{X}", "Batemos à porta com educação. Ele ficou branco quando nos viu."),
        (2, "{X}", "Está a contar desculpas. Nós estamos a contar dias de atraso."),
        (2, "LÍDER", "Mostrei-lhe as contas. Juros são juros — ele sabe as regras."),
        (2, "{X}", "Abriu o cofre pequeno atrás do quadro. Havia mais do que ele dizia."),
        (3, "{X}", "Pagamento recebido, quase completo. O resto tem data marcada."),
        (3, "LÍDER", "Aperto de mão frio. Ele não se volta a atrasar."),
    ],
    "lavagem": [
        (1, "{X}", "Reunião com o contabilista no escritório das traseiras. Livros na mesa."),
        (1, "LÍDER", "Notas em fardos, faturas em branco. Vamos dar-lhes uma vida nova."),
        (2, "{X}", "Faturação da semana inflacionada com jeito. Nada que salte à vista."),
        (2, "{X}", "Três depósitos pequenos em três agências. Sempre abaixo do radar."),
        (2, "LÍDER", "O gerente da conta fez as perguntas do costume. Recebeu as respostas do costume."),
        (3, "{X}", "Dinheiro a caminho das contas limpas. Cheira a detergente."),
        (3, "LÍDER", "Papel trilhado, história fechada. Contabilidade de artista."),
    ],
    "operacao_vip": [
        (1, "VIGIA", "O VIP chegou com dois seguranças. Mesa reservada ao fundo."),
        (1, "LÍDER", "Fato engomado, relógio no pulso. Hoje somos gente fina."),
        (2, "{X}", "Conversa aberta com o gestor dele. As nossas referências impressionaram."),
        (2, "LÍDER", "Ele quer garantias. Dei-lhe nomes que ele reconhece."),
        (2, "{X}", "Champanhe na mesa. O acordo está a tomar forma entre brindes."),
        (3, "LÍDER", "Assinatura no guardanapo vale mais que contrato. Temos negócio."),
        (3, "{X}", "Despedida com abraços. O motorista dele já trabalha para nós."),
    ],
    "suborno_oficial": [
        (1, "VIGIA", "O oficial estacionou no parque da marginal. Sem escolta, como pedido."),
        (1, "{X}", "Encontro no banco do jardim. Dois cafés, um envelope."),
        (2, "{X}", "Ele quer mais dez por cento. Previsível — está autorizado."),
        (2, "LÍDER", "Datas dos processos e nomes das testemunhas em cima da mesa."),
        (2, "{X}", "Ele confirmou: o dossier certo vai desaparecer da pilha errada."),
        (3, "{X}", "Envelope entregue, aperto de mão de três segundos. Está feito."),
        (3, "LÍDER", "Mais um amigo na máquina. Estes valem ouro nos dias maus."),
    ],
    "protecao_comercio": [
        (1, "VIGIA", "Rua do comércio a fechar. Os lojistas já nos conhecem a passada."),
        (1, "{X}", "Primeira loja: pagamento pronto em envelope, como sempre."),
        (2, "{X}", "O do talho tentou negociar. Expliquei o preço da concorrência — pagou."),
        (2, "{X}", "Loja nova na esquina. Apresentámo-nos com um sorriso e uma tabela."),
        (2, "LÍDER", "Houve um vidro partido na semana passada — tratámos do responsável. Serviço incluído."),
        (3, "{X}", "Ronda completa, caixa fechada. Zona tranquila e agradecida."),
        (3, "LÍDER", "Proteção é isto: eles dormem melhor, nós cobramos melhor."),
    ],
    "boato_rua": [
        (1, "{X}", "Café da esquina, hora de ponta. As línguas certas estão todas cá."),
        (1, "VIGIA", "O barbeiro já mordeu o isco. Aquilo espalha mais que jornal."),
        (2, "{X}", "História plantada em três mesas diferentes, com três versões ligeiramente diferentes."),
        (2, "{X}", "O taxista levou a versão picante. Amanhã já vem enfeitada de volta."),
        (2, "LÍDER", "O alvo do boato já ligou a desmentir. Tarde demais — a rua decide."),
        (3, "{X}", "Ouvi a nossa história contada de volta por um estranho. Está viva."),
        (3, "LÍDER", "Semente plantada. Em três dias é verdade absoluta em {district}."),
    ],
    "suborno_funcionario": [
        (1, "VIGIA", "O funcionário sai sempre pelas traseiras às seis. Fuma sozinho."),
        (1, "{X}", "Abordagem suave no café. Falámos da vida, das dívidas dele."),
        (2, "{X}", "Mostrei-lhe o envelope. Ele olhou três vezes para os lados — vai aceitar."),
        (2, "{X}", "Ele quer garantias de que ninguém sabe. Dei-lhe a minha palavra e mais dez por cento."),
        (2, "LÍDER", "Acesso combinado: chaves, códigos e horários das rondas internas."),
        (3, "{X}", "Primeiro pagamento entregue. Ele já está a copiar os ficheiros."),
        (3, "LÍDER", "Temos um par de olhos lá dentro. Tratem-no bem — é um investimento."),
    ],
    "chantagem_politico": [
        (1, "VIGIA", "O político jantou onde não devia, com quem não devia. Temos tudo em fotografia."),
        (1, "{X}", "Dossier entregue ao assessor com um cartão sem nome. Ele percebeu à primeira."),
        (2, "{X}", "Telefonema recebido. A voz dele tremia — bom sinal para nós."),
        (2, "LÍDER", "As exigências são simples: uma assinatura aqui, um silêncio ali."),
        (2, "{X}", "Ele tentou mandar um intermediário armado em esperto. Devolvemos com juros."),
        (3, "{X}", "Acordo fechado em garagem de hotel. Ele assinou tudo."),
        (3, "LÍDER", "Os negativos ficam connosco. Fidelidade garantida até às próximas eleições."),
    ],
    "lavagem_casino": [
        (1, "{X}", "Fichas compradas em três caixas diferentes. Notas gastas, caras novas."),
        (1, "VIGIA", "O chefe de sala é nosso. As câmaras vão ter uma noite esquecida."),
        (2, "{X}", "Duas horas de apostas mínimas nas mesas certas. Perder devagar é uma arte."),
        (2, "{X}", "Troca de fichas grandes na mesa vip. O croupier nem pestanejou."),
        (2, "LÍDER", "Cheques do casino emitidos em nomes limpos. Papel oficial, tinta fresca."),
        (3, "{X}", "Levantámos os ganhos no balcão como turistas sortudos."),
        (3, "LÍDER", "Dinheiro sujo entrou, cheque limpo saiu. A banca lavou e nem soube."),
    ],
    "infiltracao_sindicato": [
        (1, "{X}", "Reunião sindical aberta. O nosso homem entrou com a carteira de sócio nova."),
        (1, "VIGIA", "O tesoureiro é o elo fraco — divorciado, endividado, falador."),
        (2, "{X}", "Primeira conversa com o tesoureiro. Pagámos-lhe o almoço e as mágoas."),
        (2, "{X}", "Acesso à lista de membros e às quotas. Fotografado em dez minutos."),
        (2, "LÍDER", "A moção que nos interessa vai a votos na próxima assembleia — já temos os votos."),
        (3, "{X}", "O nosso homem ficou com a pasta das obras do porto. Posição perfeita."),
        (3, "LÍDER", "O sindicato agora tem dois patrões. Só um deles paga em dinheiro."),
    ],
    "acordo_autarca": [
        (1, "VIGIA", "O autarca chega ao restaurante às nove. Reservámos a sala privada."),
        (1, "LÍDER", "Plantas do novo loteamento na pasta. Ele vai gostar dos números."),
        (2, "{X}", "Ele fala de burocracia, nós falamos de percentagens. As línguas entendem-se."),
        (2, "LÍDER", "Licenças aceleradas em troca de apoio discreto à campanha. Clássico."),
        (2, "{X}", "O chefe de gabinete dele levantou objeções. Foi convidado a sair da sala."),
        (3, "LÍDER", "Acordo selado com vinho caro. As assinaturas vêm por caminhos oficiais."),
        (3, "{X}", "Saímos por portas separadas. A câmara municipal tem um novo sócio silencioso."),
    ],
    "campanha_difamacao": [
        (1, "{X}", "Material sobre o alvo compilado: dívidas, casos, fotografias infelizes."),
        (1, "VIGIA", "Três jornalistas famintos identificados. Um deles já mordeu."),
        (2, "{X}", "Primeira história plantada online com contas falsas a amplificar."),
        (2, "{X}", "O desmentido dele saiu tarde e a soar a culpa. Perfeito."),
        (2, "LÍDER", "Segunda vaga: os documentos 'encontrados' chegaram às redações certas."),
        (3, "{X}", "O alvo cancelou a agenda pública. Está em queda livre."),
        (3, "LÍDER", "Reputação demolida sem uma única impressão digital nossa."),
    ],
    "controlo_imprensa": [
        (1, "VIGIA", "O editor-chefe almoça sozinho às quintas. Mesa do canto, sempre."),
        (1, "{X}", "Sentámo-nos sem convite. Ele conhece-nos de nome — poupa apresentações."),
        (2, "{X}", "Oferta na mesa: publicidade generosa e exclusivos escolhidos a dedo."),
        (2, "LÍDER", "Em troca, certas histórias morrem na secretária dele. Simples."),
        (2, "{X}", "Ele hesitou na cláusula das capas. Dobrámos o valor — hesitação curada."),
        (3, "{X}", "Acordo verbal fechado. A primeira 'história morta' já foi enterrada."),
        (3, "LÍDER", "Amanhã as notícias dizem o que precisamos. Tinta nossa, assinatura deles."),
    ],
    "golpe_estado_local": [
        (1, "LÍDER", "Todos os fios puxados ao mesmo tempo esta noite: câmara, polícia, imprensa."),
        (1, "VIGIA", "Os vereadores comprados confirmaram presença. A sessão extraordinária vai acontecer."),
        (2, "{X}", "Dossiers comprometedores entregues aos indecisos. Decidiram-se depressa."),
        (2, "{X}", "O comandante local recebeu a chamada certa. As patrulhas vão andar distraídas."),
        (2, "LÍDER", "Votação em curso... o nosso candidato tem os números."),
        (3, "{X}", "Aprovado. O executivo local acorda amanhã com donos novos."),
        (3, "LÍDER", "O poder não se toma aos gritos — assina-se em atas. Está assinado."),
    ],
}

TYPE_BEATS.update({
    # ------------------------------------------------------------------
    # LOGÍSTICA
    # ------------------------------------------------------------------
    "transporte": [
        (1, "CONDUTOR", "Carga recolhida no ponto combinado. Reboque selado e pesado."),
        (1, "VIGIA", "Rota livre de portagens com câmara. Estradas secundárias marcadas."),
        (2, "CONDUTOR", "A manter os limites de velocidade à risca. Um camião chato é um camião invisível."),
        (2, "{X}", "Ponto de controlo à frente — desviámos pela nacional. Mais lento, mais seguro."),
        (2, "VIGIA", "Ninguém atrás de nós há trinta quilómetros. Estamos limpos."),
        (3, "CONDUTOR", "A entrar na zona de entrega. A luz do armazém está verde."),
        (3, "LÍDER", "Carga entregue, guia assinada. Trabalho de relojoaria."),
    ],
    "contrabando": [
        (1, "VIGIA", "Fronteira à vista. O turno do nosso homem começa em dez minutos."),
        (1, "CONDUTOR", "Compartimento oculto fechado. Nem um cão fareja isto."),
        (2, "{X}", "Guarda debruçou-se na janela... reconheceu a cara certa. Passámos."),
        (2, "CONDUTOR", "Do outro lado agora. A mudar de matrícula na primeira área de serviço."),
        (2, "VIGIA", "Escolta ligeira a cem metros, para o que der e vier."),
        (3, "{X}", "Mercadoria transferida para a carrinha limpa. O camião segue vazio."),
        (3, "LÍDER", "Atravessámos sem uma gota de suor. Rota de ouro, esta."),
    ],
    "entrega_expressa": [
        (1, "CONDUTOR", "Pacote a bordo. Contador a correr — isto é contra o relógio."),
        (1, "VIGIA", "Semáforos sincronizados pelo nosso homem no centro de tráfego."),
        (2, "CONDUTOR", "A cortar pela ciclovia vazia. Regras são para quem tem tempo."),
        (2, "{X}", "Cliente confirmou que está à espera. Porta das traseiras aberta."),
        (2, "VIGIA", "Uma patrulha na avenida — mudámos de rua sem drama."),
        (3, "CONDUTOR", "Entrega feita com dois minutos de margem. Recorde pessoal."),
        (3, "LÍDER", "Rápido, limpo e pago. Assim é que é uma expressa."),
    ],
    "rota_internacional": [
        (1, "VIGIA", "Contentor embarcado no navio certo. Manifesto adulterado a bordo."),
        (1, "{X}", "Contacto no porto de destino confirmado. A ponte está armada."),
        (2, "{X}", "Alfândega do país vizinho selecionou outro contentor para inspeção. Sorte comprada."),
        (2, "CONDUTOR", "Camião de recolha a postos do outro lado da fronteira."),
        (2, "VIGIA", "Rastreio do contentor a bater certo com a rota falsa. Ninguém suspeita."),
        (3, "{X}", "Carga desembarcada e recolhida sem uma pergunta."),
        (3, "LÍDER", "Três países, zero registos. Logística internacional de primeira."),
    ],
    "entrega_local": [
        (1, "CONDUTOR", "Encomenda no porta-bagagens. Cinco paragens no bairro."),
        (1, "VIGIA", "Ruas do costume, clientes do costume. Rotina."),
        (2, "{X}", "Primeira entrega feita à porta da garagem. Pagamento em mão."),
        (2, "CONDUTOR", "A saltar becos para evitar a avenida principal."),
        (2, "VIGIA", "Miúdo a olhar demais na terceira paragem — nada, é só curioso."),
        (3, "{X}", "Última entrega despachada. Carrinha vazia, bolso cheio."),
        (3, "LÍDER", "Bairro servido, ninguém reparou. Entrega ao domicílio à moda antiga."),
    ],
    "recolha_mercadoria": [
        (1, "CONDUTOR", "No ponto de recolha. O fornecedor está a carregar."),
        (1, "VIGIA", "Local calmo, sem olhares. Confirma a contagem antes de assinar."),
        (2, "{X}", "Contagem bate certo com o combinado. Qualidade verificada à amostra."),
        (2, "{X}", "Ele tentou meter duas caixas a menos. Contámos outra vez à frente dele."),
        (2, "VIGIA", "Movimento normal na rua. Um camião do lixo, nada de mais."),
        (3, "CONDUTOR", "Tudo a bordo e amarrado. A sair devagar."),
        (3, "LÍDER", "Recolha completa, contas certas. A caminho do armazém."),
    ],
    "transporte_armas": [
        (1, "CONDUTOR", "Caixas no fundo falso, cobertas de peças de máquinas. Peso disfarçado."),
        (1, "VIGIA", "Rota sem radares fixos mapeada. Só estradas cegas."),
        (2, "{X}", "Se nos mandarem parar, é entrega de peças agrícolas. Papéis a condizer."),
        (2, "CONDUTOR", "Ultrapassei uma patrulha parada. Acenei. Eles acenaram de volta."),
        (2, "VIGIA", "Cliente confirmou o ponto de troca — parque industrial, portão três."),
        (3, "{X}", "Arsenal entregue e conferido peça a peça. Cliente satisfeito."),
        (3, "LÍDER", "Ferro pesado movido sem um arranhão. Estes é que pagam bem."),
    ],
    "rota_costeira": [
        (1, "VIGIA", "Lancha no ponto de encontro ao largo. Luzes apagadas, motor ao ralenti."),
        (1, "{X}", "Fardos içados a bordo. Impermeáveis e boiantes, como pedido."),
        (2, "CONDUTOR", "A costear fora do alcance do radar da capitania."),
        (2, "VIGIA", "Barco da autoridade marítima a norte — a afastar-se. Mantemos o rumo."),
        (2, "{X}", "Enseada de desembarque à vista. A carrinha já pisca faróis da praia."),
        (3, "{X}", "Carga em terra, areia limpa atrás de nós. Maré vai apagar tudo."),
        (3, "LÍDER", "O mar não deixa rasto. Rota costeira é a mais limpa que há."),
    ],
    "contrabando_tabaco": [
        (1, "CONDUTOR", "Paletes de tabaco escondidas atrás de carga legítima de bebidas."),
        (1, "VIGIA", "Ponto de descarga é o armazém do primo. Sem faturas, sem IVA."),
        (2, "{X}", "Selos fiscais falsos aplicados a frio. Passam num relance."),
        (2, "CONDUTOR", "Fiscalização móvel na saída da autoestrada — saímos um nó antes."),
        (2, "VIGIA", "Distribuição já combinada com os cafés e as tabacarias amigas."),
        (3, "{X}", "Descarregado no armazém. Metade já tem destino amanhã de manhã."),
        (3, "LÍDER", "Cada maço é lucro puro. O Estado que fume o prejuízo."),
    ],
    "frota_fantasma": [
        (1, "VIGIA", "Três carrinhas idênticas, matrículas clonadas de veículos reais."),
        (1, "CONDUTOR", "Comboio montado. Cada uma segue rota diferente com a mesma matrícula."),
        (2, "{X}", "Se uma for filmada, há três iguais na cidade. Confusão garantida."),
        (2, "CONDUTOR", "Câmara de portagem apanhou a número dois — mas está registada limpa."),
        (2, "VIGIA", "Carga verdadeira vai na terceira, a mais anónima das três."),
        (3, "{X}", "Todas chegaram, ninguém sabe qual levava o quê."),
        (3, "LÍDER", "Uma frota que não existe nos papéis. Fantasmas com rodas."),
    ],
    "rota_alfandega": [
        (1, "VIGIA", "O inspetor comprado está de serviço no canal verde. Tudo alinhado."),
        (1, "{X}", "Documentação do contentor perfeita — origem, valor, tudo falsificado com arte."),
        (2, "{X}", "Contentor encaminhado para o canal verde. Nem raio-x, nem cão."),
        (2, "LÍDER", "O inspetor deu o toque: supervisor a passar. Abrandar dois minutos."),
        (2, "VIGIA", "Supervisor foi-se embora. Canal verde outra vez nosso."),
        (3, "{X}", "Contentor libertado com selo oficial. Carga limpa aos olhos do Estado."),
        (3, "LÍDER", "A alfândega carimbou o nosso contrabando. Não há papel mais limpo."),
    ],
    "carga_diplomatica": [
        (1, "VIGIA", "Mala com selo diplomático — imune a inspeção por tratado."),
        (1, "{X}", "O adido corrupto assinou a guia. A mala é intocável agora."),
        (2, "CONDUTOR", "Escolta com matrícula do corpo diplomático. Ninguém nos manda parar."),
        (2, "{X}", "Passámos o aeroporto pela porta vip. Nem os olhares nos tocaram."),
        (2, "VIGIA", "Carro oficial à frente a abrir caminho. Bandeirinhas e tudo."),
        (3, "{X}", "Mala entregue na embaixada-fachada. Conteúdo trocado nos bastidores."),
        (3, "LÍDER", "Imunidade diplomática é a melhor mula que o dinheiro compra."),
    ],
    "rede_distribuicao": [
        (1, "LÍDER", "Sete pontos de entrega esta noite, três equipas em paralelo."),
        (1, "VIGIA", "Central de coordenação montada. Cada carrinha reporta a cada paragem."),
        (2, "{X}", "Nós um a quatro despachados. Distribuidores a confirmar receção."),
        (2, "CONDUTOR", "Uma carrinha com pneu furado — backup já a caminho do ponto cinco."),
        (2, "LÍDER", "Fluxo de caixa a subir em tempo real. A máquina está a funcionar."),
        (3, "{X}", "Todos os pontos servidos. Rede a operar como um relógio suíço."),
        (3, "LÍDER", "Isto já não é contrabando — é uma cadeia de abastecimento."),
    ],
    "porto_franco": [
        (1, "VIGIA", "Terminal de contentores nosso por três horas. Grua e gruísta comprados."),
        (1, "{X}", "Contentores marcados a mudar de zona sem passar por registo."),
        (2, "{X}", "Mercadoria a entrar na zona franca — território sem impostos nem perguntas."),
        (2, "LÍDER", "Reetiquetagem completa. Sai daqui como produto de origem legal."),
        (2, "VIGIA", "Ronda da segurança portuária a três terminais de distância. Tempo de sobra."),
        (3, "{X}", "Contentores reintroduzidos no fluxo legal com papéis novos."),
        (3, "LÍDER", "O porto franco lavou a mercadoria melhor que qualquer banco."),
    ],
    # ------------------------------------------------------------------
    # TÉCNICA
    # ------------------------------------------------------------------
    "hack": [
        (1, "{X}", "Ligação ao gateway estabelecida. A mapear a topologia da rede."),
        (1, "{X}", "Credenciais de baixo nível capturadas por phishing interno. Estou dentro."),
        (2, "{X}", "Firewall contornada por uma porta de serviço esquecida. Escalada de privilégios em curso."),
        (2, "{X}", "Root obtido. A rede é minha — pastas a abrir uma a uma."),
        (2, "VIGIA", "Tráfego de saída mascarado por três VPNs. Origem impossível de traçar."),
        (3, "{X}", "Dados alvo extraídos e cifrados. A limpar logs de acesso."),
        (3, "LÍDER", "Saímos sem deixar pegada digital. Como se nunca tivéssemos tocado no teclado."),
    ],
    "infiltracao": [
        (1, "{X}", "Crachá clonado válido no torniquete de serviço. Estou no piso técnico."),
        (1, "VIGIA", "Câmaras do corredor em loop. Tens noventa segundos de cada vez."),
        (2, "{X}", "Sala de servidores aberta. A ligar o dispositivo à porta de manutenção."),
        (2, "{X}", "Um funcionário passou — sorri, mostrei o crachá, ele nem parou."),
        (2, "LÍDER", "Objetivo à vista. Fotografa tudo e não toques em mais nada."),
        (3, "{X}", "Dispositivo colocado e a transmitir. Retirada pela escada de serviço."),
        (3, "LÍDER", "Entrámos e saímos como pessoal da casa. Ninguém fez uma pergunta."),
    ],
    "vigilancia_digital": [
        (1, "{X}", "Alvo geolocalizado pelo telemóvel. A clonar o cartão SIM."),
        (1, "VIGIA", "Rotina dele mapeada: casa, café, escritório, amante. Previsível."),
        (2, "{X}", "Acesso à conta de nuvem dele. Fotos, mensagens, e-mails — tudo espelhado."),
        (2, "{X}", "Microfone do portátil ativado remotamente. A ouvir as reuniões dele."),
        (2, "LÍDER", "Padrões identificados. Sabemos o que ele faz antes de ele decidir."),
        (3, "{X}", "Dossier completo montado: contactos, rotinas, segredos."),
        (3, "LÍDER", "Conhecemo-lo melhor do que a mulher dele. Informação é poder."),
    ],
    "ciberataque_bancario": [
        (1, "{X}", "Túnel aberto para a rede interbancária de teste. A migrar para produção."),
        (1, "VIGIA", "Janela de manutenção noturna do banco — monitorização reduzida ao mínimo."),
        (2, "{X}", "Acesso ao sistema de transferências SWIFT. Contas-mula a postos no estrangeiro."),
        (2, "{X}", "Primeira transferência fatiada em dez para ficar abaixo dos alertas."),
        (2, "VIGIA", "Deteção de fraude ainda a dormir. Continua, devagar."),
        (3, "{X}", "Fundos aninhados em três jurisdições. A apagar o rasto das transações."),
        (3, "LÍDER", "O banco vai levar dias a perceber. Nós já cá não estamos."),
    ],
    "phishing_bancario": [
        (1, "{X}", "Site clonado do banco no ar. Idêntico ao cêntimo."),
        (1, "VIGIA", "Primeira leva de e-mails enviada. As iscas estão na água."),
        (2, "{X}", "Três vítimas já introduziram credenciais. A capturar em tempo real."),
        (2, "{X}", "Código de dupla autenticação intercetado — a agir antes de expirar."),
        (2, "LÍDER", "Transferências pequenas, muitas contas. Nada que dispare alarmes."),
        (3, "{X}", "Contas esvaziadas para as mulas. Site desligado, servidor apagado."),
        (3, "LÍDER", "Pescámos bem hoje. E o anzol desapareceu sem rasto."),
    ],
    "clonagem_cartoes": [
        (1, "{X}", "Skimmer instalado no multibanco da estação. Câmara-agulha alinhada com o teclado."),
        (1, "VIGIA", "Fluxo de clientes alto — dados a entrar depressa."),
        (2, "{X}", "Já temos duzentas bandas magnéticas e respetivos PIN. Colheita farta."),
        (2, "{X}", "Cartões em branco a serem gravados na carrinha. Linha de montagem."),
        (2, "VIGIA", "Técnico do banco a aproximar-se — recolhemos o skimmer a tempo."),
        (3, "{X}", "Levantamentos coordenados em caixas de três cidades ao mesmo tempo."),
        (3, "LÍDER", "Plástico virou dinheiro. Antes que cancelem, já gastámos."),
    ],
    "hack_semaforos": [
        (1, "{X}", "Acesso à central de gestão de tráfego. Estou na consola dos semáforos."),
        (1, "VIGIA", "Precisamos da avenida verde e das laterais vermelhas. A postos."),
        (2, "{X}", "Corredor verde criado na rota de fuga. Vamos voar pela cidade."),
        (2, "{X}", "Cruzamento do alvo congelado em vermelho — ninguém nos segue por ali."),
        (2, "LÍDER", "Câmaras de trânsito em pausa programada. Sem fotografias."),
        (3, "{X}", "A repor o sistema no horário normal. Ninguém vai notar os dois minutos."),
        (3, "LÍDER", "A cidade abriu-nos as portas. Literalmente."),
    ],
    "fraude_criptomoedas": [
        (1, "{X}", "Contrato inteligente malicioso publicado. Interface promete lua e estrelas."),
        (1, "VIGIA", "Influenciadores pagos já estão a bombar o token nas redes."),
        (2, "{X}", "Liquidez a entrar depressa. Os investidores estão em euforia."),
        (2, "{X}", "Carteira de reserva a encher. A preparar a função de saída."),
        (2, "LÍDER", "Esperem o pico. Ganância deles é o nosso lucro."),
        (3, "{X}", "Liquidez drenada num bloco. O gráfico foi para o inferno."),
        (3, "LÍDER", "Puxámos o tapete no momento certo. Cripto: o velho golpe com casaco novo."),
    ],
    "invasao_servidor": [
        (1, "{X}", "Vulnerabilidade de dia-zero no servidor exposto. A lançar o exploit."),
        (1, "VIGIA", "Administrador de sistemas offline há uma hora. Janela aberta."),
        (2, "{X}", "Shell obtida. A escalar para administrador de domínio."),
        (2, "{X}", "Base de dados inteira a ser espelhada para o nosso servidor."),
        (2, "LÍDER", "Instala a porta traseira. Vamos querer voltar aqui."),
        (3, "{X}", "Backdoor persistente instalada, logs sanitizados."),
        (3, "LÍDER", "Somos donos do servidor deles. E eles pagam a eletricidade."),
    ],
    "ciberespionagem": [
        (1, "{X}", "Rede corporativa do alvo penetrada via portátil de um comercial."),
        (1, "VIGIA", "Segmento de I&D é o que interessa. A procurar a porta certa."),
        (2, "{X}", "Servidor de patentes localizado. Documentos confidenciais a fluir."),
        (2, "{X}", "E-mails da administração intercetados — a fusão deles é notícia velha para nós."),
        (2, "LÍDER", "Só o que o cliente encomendou. Não deixes migalhas."),
        (3, "{X}", "Segredos industriais empacotados e cifrados. Rasto apagado."),
        (3, "LÍDER", "Anos de investigação deles, nossos numa noite. A concorrência agradece."),
    ],
    "ataque_ddos": [
        (1, "{X}", "Botnet acordada — cem mil dispositivos a postos em todo o mundo."),
        (1, "VIGIA", "Alvo confirmado: a plataforma deles no pico de tráfego. Cronometra."),
        (2, "{X}", "Primeira vaga lançada. Latência deles a disparar já."),
        (2, "{X}", "Mitigação deles ativou — a mudar de vetor para camada de aplicação."),
        (2, "LÍDER", "Mantém a pressão. O cliente quer o site deles no chão à hora do anúncio."),
        (3, "{X}", "Serviço deles caído por completo. Manchete garantida."),
        (3, "LÍDER", "Silenciámos a internet deles com um clique. Botnet de volta a dormir."),
    ],
    "roubo_dados": [
        (1, "{X}", "Base de dados de clientes localizada. Milhões de registos à espera."),
        (1, "VIGIA", "Sistema de deteção de exfiltração é o obstáculo. A estudá-lo."),
        (2, "{X}", "A extrair em pacotes pequenos disfarçados de tráfego normal. Lento mas invisível."),
        (2, "{X}", "Metade da base já saiu. Cartões, moradas, palavras-passe — tudo."),
        (2, "LÍDER", "Sem pressas. Um pico de tráfego acorda a segurança."),
        (3, "{X}", "Dump completo cifrado no nosso lado. Rasto de extração diluído."),
        (3, "LÍDER", "Os dados deles valem uma fortuna no mercado certo. E já são nossos."),
    ],
    "sabotagem_industrial": [
        (1, "{X}", "Acesso ao sistema de controlo industrial da fábrica. Estou nos autómatos."),
        (1, "VIGIA", "Turno da noite com meia dúzia de operários. Reação lenta garantida."),
        (2, "{X}", "Parâmetros da linha de produção alterados subtilmente — defeitos que só aparecem depois."),
        (2, "{X}", "Sistema de refrigeração da caldeira reprogramado. Vai sobreaquecer sozinho."),
        (2, "LÍDER", "Nada de espetáculos. Queremos que pareça avaria, não sabotagem."),
        (3, "{X}", "Alterações camufladas como falha de manutenção. Logs a condizer."),
        (3, "LÍDER", "A concorrência deles vai perder o contrato do ano. Acidente infeliz."),
    ],
    "guerra_cibernetica": [
        (1, "LÍDER", "Operação em cinco frentes: rede, energia, comunicações, finanças, imprensa."),
        (1, "VIGIA", "Todas as equipas técnicas sincronizadas ao segundo. Contagem decrescente."),
        (2, "{X}", "Infraestrutura de rede deles a cair setor a setor. Caos coordenado."),
        (2, "{X}", "Sistemas financeiros congelados, comunicações internas mudas."),
        (2, "LÍDER", "Mantém o apagão. Que sintam o que é perder o controlo."),
        (3, "{X}", "Objetivos cumpridos. A retirar de todas as frentes em simultâneo."),
        (3, "LÍDER", "Derrubámos um império sem disparar um tiro. Guerra do século vinte e um."),
    ],
})

TYPE_BEATS.update({
    # ------------------------------------------------------------------
    # ESPECIAL
    # ------------------------------------------------------------------
    "missao_especial": [
        (1, "VIGIA", "Perímetro do alvo analisado ao pormenor. Plano em execução — fase um."),
        (1, "LÍDER", "Isto não é um trabalho qualquer. Cada movimento foi ensaiado."),
        (2, "{X}", "Fase um concluída sem um ruído. A avançar para o núcleo."),
        (2, "{X}", "Acesso ao objetivo principal garantido. Isto é maior do que pensávamos."),
        (2, "LÍDER", "Mantenham a disciplina. É agora que os amadores falham."),
        (3, "{X}", "Objetivo seguro. A iniciar extração conforme o ensaio."),
        (3, "LÍDER", "Missão cumprida como no papel. Profissionais fazem parecer fácil."),
    ],
    "roubo_obra_arte": [
        (1, "VIGIA", "Galeria privada, coleção sob seguro milionário. Alarme volumétrico ativo."),
        (1, "{X}", "Feixes laser mapeados com fumo. Passagem estreita mas possível."),
        (2, "{X}", "A peça está fora da moldura. Detetor de humidade enganado com pano húmido."),
        (2, "{X}", "Substituí por uma réplica de galeria. O peso engana o sensor de base."),
        (2, "LÍDER", "Só a obra da lista. O resto é isco para amadores."),
        (3, "VIGIA", "Ronda do segurança daqui a noventa segundos. A sair já."),
        (3, "LÍDER", "Uma obra-prima trocada por uma cópia. O museu que descubra sozinho."),
    ],
    "operacao_encoberta": [
        (1, "LÍDER", "Identidades falsas verificadas. A partir de agora, somos outras pessoas."),
        (1, "VIGIA", "Cobertura montada, história de fachada à prova de bala."),
        (2, "{X}", "Infiltrados no evento sem levantar suspeitas. Estamos a circular."),
        (2, "{X}", "Contacto feito com o alvo. Ele engoliu a nossa fachada por inteiro."),
        (2, "LÍDER", "Não quebrem o personagem. Um deslize e cai tudo."),
        (3, "{X}", "Objetivo alcançado sob disfarce. A retirar sem desfazer as identidades."),
        (3, "LÍDER", "Nunca lá estivemos, nunca fomos nós. Encoberta é isto."),
    ],
    "resgate_refem": [
        (1, "VIGIA", "Refém localizado no segundo andar. Três guardas rotativos identificados."),
        (1, "LÍDER", "Entrada silenciosa. Ninguém dispara sem o meu sinal."),
        (2, "{X}", "Primeiro guarda neutralizado sem barulho. A avançar pelo corredor."),
        (2, "{X}", "Refém contactado — está lúcido e pronto a mover-se. Bom sinal."),
        (2, "LÍDER", "Segundo e terceiro tratados. Corredor livre até à saída."),
        (3, "{X}", "Refém em segurança na carrinha. Sem um arranhão."),
        (3, "LÍDER", "Entrámos, tirámos, saímos. O cliente vai chorar de alegria — e pagar."),
    ],
    "leilao_clandestino": [
        (1, "VIGIA", "Leilão a decorrer na cave. Compradores armados, todos de máscara."),
        (1, "{X}", "Entrámos como licitadores. O nosso número de licitação é o dezassete."),
        (2, "{X}", "O lote que interessa vai a leilão a seguir. A preparar o lance."),
        (2, "LÍDER", "Se der para comprar, compramos. Se não, levamos à mesma."),
        (2, "{X}", "Lance vencedor nosso — mas com dinheiro que vamos recuperar à saída."),
        (3, "{X}", "Lote na mala e organizadores 'reembolsados' à força na garagem."),
        (3, "LÍDER", "Comprámos e ficámos com o dinheiro. Melhor leilão de sempre."),
    ],
    "venda_armamento": [
        (1, "VIGIA", "Comprador chegou com escolta pesada. Dois carros, seis homens."),
        (1, "LÍDER", "Mercadoria no camião, à mostra mas fora de alcance. Regras deles, condições nossas."),
        (2, "{X}", "Inspeção da amostra feita. Ele está satisfeito com a qualidade."),
        (2, "LÍDER", "Contagem do dinheiro primeiro. Só depois se abre o resto do camião."),
        (2, "VIGIA", "Atiradores nossos nos telhados, caso ele tenha ideias."),
        (3, "{X}", "Pagamento verificado, mercadoria transferida. Negócio limpo."),
        (3, "LÍDER", "Retirada em ordem inversa. Cada um sai pelo lado por onde entrou."),
    ],
    "fuga_prisao": [
        (1, "VIGIA", "Guarda subornado no turno da noite. Câmara do pátio em manutenção 'acidental'."),
        (1, "{X}", "Carrinha de manutenção posicionada junto ao muro leste."),
        (2, "{X}", "O nosso homem saiu da ala pela porta que ficou 'esquecida' aberta."),
        (2, "CONDUTOR", "Escada dobrável no muro. Ele está a subir — mais depressa!"),
        (2, "VIGIA", "Contagem dos guardas daqui a seis minutos. Temos margem, mas apertada."),
        (3, "{X}", "A bordo, uniforme trocado por roupa de rua. Rumo à casa segura."),
        (3, "LÍDER", "Um homem a menos na contagem deles, um a mais na família. Recuperado."),
    ],
    "assassinato_contrato": [
        (1, "VIGIA", "Alvo confirmado na rotina de sempre. Janela de ação: quatro minutos."),
        (1, "LÍDER", "Limpo e cirúrgico. Entramos, resolvemos, desaparecemos."),
        (2, "{X}", "Posição de tiro montada. Linha de visão limpa até ao alvo."),
        (2, "{X}", "Escolta dele distraída pela chamada falsa que plantámos. Agora."),
        (2, "LÍDER", "Confirmado. A recolher casquilhos e a apagar presença."),
        (3, "CONDUTOR", "Rota de fuga em três trocas de veículo já a decorrer."),
        (3, "LÍDER", "Contrato cumprido. O cliente que transfira o resto — sabe as consequências se não."),
    ],
    "golpe_banco_central": [
        (1, "LÍDER", "O maior golpe de sempre. Câmara-forte subterrânea, três anéis de segurança."),
        (1, "{X}", "Sistema de segurança principal em nossas mãos — o interno vendeu tudo."),
        (2, "{X}", "Primeiro anel neutralizado. A descer para a câmara-forte."),
        (2, "{X}", "Porta de aço de meio metro. Carga moldada colocada nos gonzos."),
        (2, "LÍDER", "Lingotes e notas em série antiga. Só o que cabe e vale. Cronómetro implacável."),
        (3, "{X}", "Carga transferida para o túnel de saída. A selar atrás de nós."),
        (3, "LÍDER", "Acabámos de roubar o coração do sistema. Nada volta a ser igual."),
    ],
    "trafico_influencia_internacional": [
        (1, "LÍDER", "Cimeira privada, delegações de três países. Todos com preço."),
        (1, "VIGIA", "Os intermediários certos identificados. Cada um abre uma porta diferente."),
        (2, "{X}", "Primeiro acordo fechado — concessões em troca de contratos nossos."),
        (2, "{X}", "O contacto do segundo país exigiu offshore. Já está tratado."),
        (2, "LÍDER", "Isto tece-se com paciência. Cada favor devolvido dez vezes maior."),
        (3, "{X}", "Rede de influência montada em três capitais. Documentação segura."),
        (3, "LÍDER", "Compramos ministros como quem compra pão. O mundo é um mercado."),
    ],
    "operacao_fantasma": [
        (1, "LÍDER", "Operação sem rasto. Nada em papel, nada em digital, ninguém sabe nomes."),
        (1, "VIGIA", "Comunicações só por rádio cifrado descartável. Silêncio total lá fora."),
        (2, "{X}", "Fase encoberta em curso. Nem os nossos próprios registos vão guardar isto."),
        (2, "{X}", "Objetivo atingido sem uma única testemunha consciente."),
        (2, "LÍDER", "Apaguem tudo à passagem. Não deixamos nem uma sombra."),
        (3, "{X}", "Retirada limpa. Equipamento destruído, rádios ao rio."),
        (3, "LÍDER", "Esta operação nunca aconteceu. E é assim que fica."),
    ],
})
